### ISSUE TITLE
Empty search should still obey filter/sort

### ISSUE THREAD

**Issue by ryantmer** [Brightspace/d2l-my-courses-ui#250] opened 2016-12-21 17:02 UTC
When the search is empty, it currently ignores the filter and sort that have been selected. It's possible that clicking the X to clear the search should also clear the filter and reset the sort back to the default ordering. However, if the user simply deletes their search, it seems like the query should still obey the `parentOrganizations` from the filter menu.

**Comment by apalaniuk** [comment] 2016-12-22 22:12
This looks to be fixed as of #252.

**Comment by apalaniuk** [comment] 2016-12-22 22:17
~~This looks to be fixed as of #252.~~

Nevermind; the issue isn't when the search is empty, but when it's cleared using the button in the search bar.

**Comment by apalaniuk** [comment] 2017-01-13 02:20
Fixed in #267

**Closed by apalaniuk** 2017-01-13 02:20 UTC
Labels: enhancement
